[tool.poetry]
name = "training"
version = "0.1.0"
description = "Training for sumosim robots"
authors = ["wwagner4"]
license = "apache2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyter = "^1.0.0"
dataclasses-json = "^0.6.4"
typer = "^0.12.3"
ruff = "^0.4.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

